/**
 * Generated imagery, behind a pluggable adapter.
 *
 * Five adapters ship:
 *   openai     — OpenAI Images API            (OPENAI_API_KEY)
 *   grok       — xAI grok-imagine-image       (XAI_API_KEY)
 *   gemini     — Google Gemini image models   (GOOGLE_API_KEY, needs billing)
 *   fal        — fal.ai hosted models         (FAL_KEY)
 *   procedural — deterministic abstract artwork rendered locally, no key,
 *                no network
 *
 * All four real backends return generated bytes; the differences are in how
 * output shape is requested (`aspect_ratio`, `imageConfig.aspectRatio`, named
 * size presets) and whether bytes come back inline or as a URL to download.
 * `nearestAspectLabel` hides that so the generator only ever asks for a ratio.
 *
 * A word on `procedural`, because the honesty matters: it is **not** AI. It is
 * a gradient-and-geometry generator that exists so `imageSource: "ai"` still
 * produces correctly-sized, valid, visually-varied images when no generation
 * key is configured — which keeps the tool usable out of the box and the
 * integration tests hermetic. Every image it produces carries a `credit` that
 * says exactly what it is, so it can never be mistaken for generated art.
 *
 * Adding a new backend (Replicate, Stability, a local diffusion server) means
 * implementing `AiImageAdapter` and registering it in `selectAiAdapter`.
 */

import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { ThemeseedError } from '../core/errors.js';
import { logger } from '../core/logger.js';
import type { ImageRef, ImageRequest } from '../core/types.js';
import { probeImage } from './inspect.js';
import { encodePng, hashString, seededRandom } from './png.js';
import { orientationFor, type ImageSource } from './source.js';

export type AiAdapterName = 'openai' | 'grok' | 'gemini' | 'fal' | 'procedural';

export interface GeneratedImage {
  bytes: Uint8Array;
  /** File extension without the dot. */
  extension: string;
  /** Provenance, surfaced on every `ImageRef`. */
  credit: string;
}

export interface AiImageAdapter {
  readonly name: AiAdapterName;
  isConfigured(): boolean;
  configurationHint(): string;
  generate(request: ImageRequest, count: number): Promise<GeneratedImage[]>;
}

export interface AiImageSourceOptions {
  adapter?: AiAdapterName | AiImageAdapter;
  openaiApiKey?: string;
  /** xAI (Grok) key — `XAI_API_KEY`. */
  xaiApiKey?: string;
  /** Google AI Studio key — `GOOGLE_API_KEY`. */
  googleApiKey?: string;
  /** fal.ai key, in `<id>:<secret>` form — `FAL_KEY`. */
  falKey?: string;
  /** Override the model an adapter uses. */
  model?: string;
  /** Where generated files are written. Defaults to a temp directory. */
  outputDir?: string;
  fetchImpl?: typeof fetch;
}

export class AiImageSource implements ImageSource {
  readonly kind = 'ai' as const;

  private readonly adapter: AiImageAdapter;
  private readonly outputDir: string;

  constructor(options: AiImageSourceOptions = {}) {
    this.adapter =
      typeof options.adapter === 'object' ? options.adapter : selectAiAdapter(options);
    this.outputDir = options.outputDir ?? path.join(os.tmpdir(), 'themeseed-images');
  }

  get adapterName(): AiAdapterName {
    return this.adapter.name;
  }

  async isAvailable(): Promise<boolean> {
    return this.adapter.isConfigured();
  }

  async unavailableReason(): Promise<string> {
    return this.adapter.isConfigured() ? '' : this.adapter.configurationHint();
  }

  async fetch(request: ImageRequest, count: number): Promise<ImageRef[]> {
    if (!this.adapter.isConfigured()) {
      throw new ThemeseedError(
        `AI image adapter "${this.adapter.name}" is not configured`,
        {
          code: 'AI_NOT_CONFIGURED',
          hint: this.adapter.configurationHint(),
        }
      );
    }

    const generated = await this.adapter.generate(request, count);
    await fs.mkdir(this.outputDir, { recursive: true });

    const refs: ImageRef[] = [];
    for (const [index, image] of generated.entries()) {
      // Never hand a provider bytes we have not verified are an image; a failed
      // generation that returns a JSON error body would otherwise be uploaded.
      const info = probeImage(image.bytes);
      if (!info) {
        logger.warn(
          `${this.adapter.name} returned data that is not a valid image; skipping`
        );
        continue;
      }
      const name = `${hashString(`${request.query}#${index}`).toString(36)}.${image.extension}`;
      const file = path.join(this.outputDir, name);
      await fs.writeFile(file, image.bytes);
      refs.push({
        kind: 'file',
        location: file,
        width: info.width,
        height: info.height,
        alt: request.query,
        credit: image.credit,
        source: 'ai',
      });
    }
    return refs;
  }
}

export function selectAiAdapter(options: AiImageSourceOptions = {}): AiImageAdapter {
  const requested =
    (typeof options.adapter === 'string' ? options.adapter : undefined) ??
    (process.env.THEMESEED_AI_IMAGE_ADAPTER as AiAdapterName | undefined);

  const keys = {
    openai: options.openaiApiKey ?? process.env.OPENAI_API_KEY,
    grok: options.xaiApiKey ?? process.env.XAI_API_KEY,
    gemini: options.googleApiKey ?? process.env.GOOGLE_API_KEY,
    fal: options.falKey ?? process.env.FAL_KEY,
  };
  const model = options.model ?? process.env.THEMESEED_AI_IMAGE_MODEL;
  const fetchImpl = options.fetchImpl;

  const build = (name: AiAdapterName): AiImageAdapter => {
    switch (name) {
      case 'openai':
        return new OpenAiImageAdapter(keys.openai, fetchImpl, model);
      case 'grok':
        return new GrokImageAdapter(keys.grok, fetchImpl, model);
      case 'gemini':
        return new GeminiImageAdapter(keys.gemini, fetchImpl, model);
      case 'fal':
        return new FalImageAdapter(keys.fal, fetchImpl, model);
      case 'procedural':
        return new ProceduralImageAdapter();
    }
  };

  // An explicit choice is honoured even when its key is missing, so a
  // misconfiguration reports "not configured" rather than silently running on
  // a different provider than the one that was asked for.
  if (requested) return build(requested);

  // Otherwise take the first provider that has a key. Ordered by how well the
  // adapter controls output shape, which is what themes care about.
  for (const name of ['openai', 'grok', 'gemini', 'fal'] as const) {
    if (keys[name]) return build(name);
  }

  logger.debug(
    'no image-generation key configured; the "ai" source will render procedural placeholders'
  );
  return new ProceduralImageAdapter();
}

/**
 * Maps a requested ratio onto the nearest `w:h` string a provider accepts.
 * Providers reject arbitrary ratios, so snapping to a supported one beats
 * having the request fail or silently return a square.
 */
export function nearestAspectLabel(
  request: ImageRequest,
  supported: readonly string[]
): string {
  const orientation = orientationFor(request);
  const target =
    request.aspectRatio ??
    (orientation === 'portrait' ? 0.75 : orientation === 'square' ? 1 : 1.5);

  let best = supported[0]!;
  let bestDelta = Infinity;
  for (const label of supported) {
    const [w, h] = label.split(':').map(Number);
    if (!w || !h) continue;
    const delta = Math.abs(w / h - target);
    if (delta < bestDelta) {
      bestDelta = delta;
      best = label;
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// OpenAI
// ---------------------------------------------------------------------------

class OpenAiImageAdapter implements AiImageAdapter {
  readonly name = 'openai' as const;

  constructor(
    private readonly apiKey: string | undefined,
    private readonly doFetch: typeof fetch = fetch,
    private readonly model = 'gpt-image-1'
  ) {}

  isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  configurationHint(): string {
    return 'Set OPENAI_API_KEY, or pick another adapter with THEMESEED_AI_IMAGE_ADAPTER (grok, gemini, fal, procedural).';
  }

  async generate(request: ImageRequest, count: number): Promise<GeneratedImage[]> {
    const response = await this.doFetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        prompt: buildPrompt(request),
        n: Math.min(count, 10),
        size: sizeFor(request),
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      throw new ThemeseedError(`Image generation failed with HTTP ${response.status}`, {
        code: 'AI_GENERATION_FAILED',
        hint: body.slice(0, 200),
      });
    }

    const data = (await response.json()) as {
      data?: Array<{ b64_json?: string; url?: string }>;
    };
    const images: GeneratedImage[] = [];

    for (const entry of data.data ?? []) {
      if (entry.b64_json) {
        images.push({
          bytes: new Uint8Array(Buffer.from(entry.b64_json, 'base64')),
          extension: 'png',
          credit: `Image generated with OpenAI ${this.model}`,
        });
      } else if (entry.url) {
        const download = await this.doFetch(entry.url);
        if (!download.ok) continue;
        images.push({
          bytes: new Uint8Array(await download.arrayBuffer()),
          extension: 'png',
          credit: `Image generated with OpenAI ${this.model}`,
        });
      }
    }
    return images;
  }
}

// ---------------------------------------------------------------------------
// xAI (Grok)
// ---------------------------------------------------------------------------

/** Ratios `grok-imagine-image` was observed to honour. */
const GROK_RATIOS = ['1:1', '4:3', '3:2', '16:9', '21:9', '3:4', '2:3', '9:16'] as const;

class GrokImageAdapter implements AiImageAdapter {
  readonly name = 'grok' as const;

  constructor(
    private readonly apiKey: string | undefined,
    private readonly doFetch: typeof fetch = fetch,
    private readonly model = 'grok-imagine-image'
  ) {}

  isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  configurationHint(): string {
    return 'Set XAI_API_KEY. Keys are issued at https://console.x.ai/.';
  }

  async generate(request: ImageRequest, count: number): Promise<GeneratedImage[]> {
    // xAI mirrors OpenAI's images endpoint but rejects `size`; shape is set
    // with `aspect_ratio`, and the default is 16:9.
    const response = await this.doFetch('https://api.x.ai/v1/images/generations', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: this.model,
        prompt: buildPrompt(request),
        n: Math.min(count, 10),
        response_format: 'b64_json',
        aspect_ratio: nearestAspectLabel(request, GROK_RATIOS),
      }),
    });

    if (!response.ok) {
      throw new ThemeseedError(
        `Grok image generation failed with HTTP ${response.status}`,
        {
          code: 'AI_GENERATION_FAILED',
          hint: (await response.text()).slice(0, 200),
        }
      );
    }

    const data = (await response.json()) as {
      data?: Array<{ b64_json?: string; mime_type?: string; url?: string }>;
    };

    const images: GeneratedImage[] = [];
    for (const entry of data.data ?? []) {
      const bytes = await this.bytesFor(entry);
      if (!bytes) continue;
      images.push({
        bytes,
        extension: entry.mime_type?.includes('png') ? 'png' : 'jpg',
        credit: `Image generated with xAI ${this.model}`,
      });
    }
    return images;
  }

  private async bytesFor(entry: {
    b64_json?: string;
    url?: string;
  }): Promise<Uint8Array | null> {
    if (entry.b64_json) return new Uint8Array(Buffer.from(entry.b64_json, 'base64'));
    if (!entry.url) return null;
    const download = await this.doFetch(entry.url);
    if (!download.ok) return null;
    return new Uint8Array(await download.arrayBuffer());
  }
}

// ---------------------------------------------------------------------------
// Google (Gemini / Imagen)
// ---------------------------------------------------------------------------

const GEMINI_RATIOS = [
  '1:1',
  '4:3',
  '3:2',
  '16:9',
  '21:9',
  '3:4',
  '2:3',
  '9:16',
] as const;

class GeminiImageAdapter implements AiImageAdapter {
  readonly name = 'gemini' as const;

  constructor(
    private readonly apiKey: string | undefined,
    private readonly doFetch: typeof fetch = fetch,
    private readonly model = 'gemini-2.5-flash-image'
  ) {}

  isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  configurationHint(): string {
    return 'Set GOOGLE_API_KEY from https://aistudio.google.com/apikey. Image generation needs billing enabled — a key without it returns 429 RESOURCE_EXHAUSTED immediately.';
  }

  async generate(request: ImageRequest, count: number): Promise<GeneratedImage[]> {
    // generateContent returns a single image per call, so `count` becomes
    // sequential requests rather than a batch parameter.
    const images: GeneratedImage[] = [];
    for (let index = 0; index < count; index++) {
      const image = await this.generateOne(request, index);
      if (image) images.push(image);
    }
    return images;
  }

  private async generateOne(
    request: ImageRequest,
    index: number
  ): Promise<GeneratedImage | null> {
    const url =
      `https://generativelanguage.googleapis.com/v1beta/models/` +
      `${encodeURIComponent(this.model)}:generateContent?key=${encodeURIComponent(this.apiKey ?? '')}`;

    const response = await this.doFetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        // Varying the prompt per index is what stops a gallery being three
        // copies of the same picture — the API has no seed parameter.
        contents: [
          { parts: [{ text: `${buildPrompt(request)} (variation ${index + 1})` }] },
        ],
        generationConfig: {
          responseModalities: ['IMAGE'],
          imageConfig: { aspectRatio: nearestAspectLabel(request, GEMINI_RATIOS) },
        },
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      throw new ThemeseedError(
        `Gemini image generation failed with HTTP ${response.status}`,
        {
          code: 'AI_GENERATION_FAILED',
          hint:
            response.status === 429
              ? 'Quota exhausted. Google image models require billing to be enabled on the project.'
              : body.slice(0, 200),
        }
      );
    }

    const data = (await response.json()) as {
      candidates?: Array<{
        content?: {
          parts?: Array<{ inlineData?: { mimeType?: string; data?: string } }>;
        };
      }>;
    };

    for (const part of data.candidates?.[0]?.content?.parts ?? []) {
      const inline = part.inlineData;
      if (!inline?.data) continue;
      return {
        bytes: new Uint8Array(Buffer.from(inline.data, 'base64')),
        extension: inline.mimeType?.includes('png') ? 'png' : 'jpg',
        credit: `Image generated with Google ${this.model}`,
      };
    }

    // A safety block returns 200 with no image part rather than an error.
    logger.warn(`Gemini returned no image for "${request.query}" (possibly filtered)`);
    return null;
  }
}

// ---------------------------------------------------------------------------
// fal.ai
// ---------------------------------------------------------------------------

class FalImageAdapter implements AiImageAdapter {
  readonly name = 'fal' as const;

  constructor(
    private readonly apiKey: string | undefined,
    private readonly doFetch: typeof fetch = fetch,
    private readonly model = 'fal-ai/flux/schnell'
  ) {}

  isConfigured(): boolean {
    return Boolean(this.apiKey);
  }

  configurationHint(): string {
    return 'Set FAL_KEY (in "<id>:<secret>" form) from https://fal.ai/dashboard/keys.';
  }

  async generate(request: ImageRequest, count: number): Promise<GeneratedImage[]> {
    const response = await this.doFetch(`https://fal.run/${this.model}`, {
      method: 'POST',
      headers: {
        // fal uses "Key <token>", not "Bearer".
        Authorization: `Key ${this.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: buildPrompt(request),
        num_images: Math.min(count, 4),
        image_size: falImageSize(request),
        enable_safety_checker: true,
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      throw new ThemeseedError(
        `fal image generation failed with HTTP ${response.status}`,
        {
          code: 'AI_GENERATION_FAILED',
          hint:
            response.status === 401
              ? 'fal rejected the key. Check FAL_KEY is current and in "<id>:<secret>" form.'
              : body.slice(0, 200),
        }
      );
    }

    const data = (await response.json()) as {
      images?: Array<{ url?: string; content_type?: string }>;
    };

    // fal returns hosted URLs rather than bytes, so each one is downloaded.
    const images: GeneratedImage[] = [];
    for (const entry of data.images ?? []) {
      if (!entry.url) continue;
      const download = await this.doFetch(entry.url);
      if (!download.ok) continue;
      images.push({
        bytes: new Uint8Array(await download.arrayBuffer()),
        extension: entry.content_type?.includes('png') ? 'png' : 'jpg',
        credit: `Image generated with ${this.model} on fal.ai`,
      });
    }
    return images;
  }
}

/** fal takes named size presets rather than a free-form ratio. */
export function falImageSize(request: ImageRequest): string {
  const orientation = orientationFor(request);
  const ratio =
    request.aspectRatio ??
    (orientation === 'portrait' ? 0.75 : orientation === 'square' ? 1 : 1.5);
  if (orientation === 'square') return 'square_hd';
  if (orientation === 'portrait') return ratio < 0.65 ? 'portrait_16_9' : 'portrait_4_3';
  return ratio > 1.6 ? 'landscape_16_9' : 'landscape_4_3';
}

function buildPrompt(request: ImageRequest): string {
  const framing =
    request.role === 'feature'
      ? 'A striking editorial hero photograph'
      : request.role === 'gallery'
        ? 'A photograph suitable for a magazine gallery'
        : 'A clean editorial photograph';
  return `${framing} illustrating: ${request.query}. Natural lighting, shallow depth of field, no text or watermarks, no visible logos.`;
}

/** The Images API accepts a fixed set of sizes; map orientation onto them. */
function sizeFor(request: ImageRequest): string {
  const orientation = orientationFor(request);
  if (orientation === 'portrait') return '1024x1536';
  if (orientation === 'square') return '1024x1024';
  return '1536x1024';
}

// ---------------------------------------------------------------------------
// Procedural (keyless fallback — deliberately not AI)
// ---------------------------------------------------------------------------

export class ProceduralImageAdapter implements AiImageAdapter {
  readonly name = 'procedural' as const;

  isConfigured(): boolean {
    return true;
  }

  configurationHint(): string {
    return '';
  }

  async generate(request: ImageRequest, count: number): Promise<GeneratedImage[]> {
    const { width, height } = dimensionsFor(request);
    const images: GeneratedImage[] = [];

    for (let index = 0; index < count; index++) {
      const seed = hashString(`${request.query}#${index}`);
      images.push({
        bytes: renderArtwork(width, height, seed),
        extension: 'png',
        credit:
          'Procedurally generated placeholder (not AI — set OPENAI_API_KEY, XAI_API_KEY, ' +
          'GOOGLE_API_KEY or FAL_KEY to generate real imagery)',
      });
    }
    return images;
  }
}

/**
 * Renders a soft two-tone gradient with a few translucent geometric shapes.
 * The goal is something that reads as "a photo goes here" at thumbnail size
 * without pretending to be a photograph.
 */
function renderArtwork(width: number, height: number, seed: number): Uint8Array {
  const random = seededRandom(seed);

  // Two hues a pleasing distance apart on the wheel.
  const baseHue = random() * 360;
  const accentHue = (baseHue + 40 + random() * 80) % 360;
  const from = hslToRgb(baseHue, 0.45 + random() * 0.2, 0.72 + random() * 0.12);
  const to = hslToRgb(accentHue, 0.5 + random() * 0.2, 0.34 + random() * 0.14);

  const shapes = Array.from({ length: 3 + Math.floor(random() * 3) }, () => ({
    cx: random() * width,
    cy: random() * height,
    radius: (0.12 + random() * 0.28) * Math.min(width, height),
    color: hslToRgb((baseHue + random() * 120) % 360, 0.5, 0.5 + random() * 0.3),
    alpha: 0.12 + random() * 0.18,
  }));

  const angle = random() * Math.PI;
  const dx = Math.cos(angle);
  const dy = Math.sin(angle);
  const span = Math.abs(dx) * width + Math.abs(dy) * height;

  return encodePng(width, height, (x, y) => {
    const t = clamp01((x * dx + y * dy) / (span || 1));
    let r = from.r + (to.r - from.r) * t;
    let g = from.g + (to.g - from.g) * t;
    let b = from.b + (to.b - from.b) * t;

    for (const shape of shapes) {
      const distance = Math.hypot(x - shape.cx, y - shape.cy);
      if (distance > shape.radius) continue;
      // Feather the edge so shapes read as soft light, not hard circles.
      const falloff = 1 - distance / shape.radius;
      const alpha = shape.alpha * falloff * falloff;
      r += (shape.color.r - r) * alpha;
      g += (shape.color.g - g) * alpha;
      b += (shape.color.b - b) * alpha;
    }

    // Ordered dithering breaks up gradient banding. Deliberately not random
    // noise: random grain is pure entropy and inflates the deflate stream by
    // roughly 10x (a 1200x800 gradient goes from ~90KB to ~900KB), while a
    // repeating 4x4 pattern costs almost nothing to compress.
    const dither = BAYER_4X4[(y & 3) * 4 + (x & 3)]! / 16 - 0.5;
    const offset = dither * 2;
    return { r: r + offset, g: g + offset, b: b + offset };
  });
}

/** Standard 4x4 Bayer threshold matrix. */
const BAYER_4X4 = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5];

function dimensionsFor(request: ImageRequest): { width: number; height: number } {
  const orientation = orientationFor(request);
  const ratio =
    request.aspectRatio ??
    (orientation === 'portrait' ? 0.75 : orientation === 'square' ? 1 : 1.5);
  // 1600px wide is enough for a hero on a 2x display without making the PNG
  // encoder the slowest part of a seed run.
  const width = Math.min(request.minWidth ?? 1600, 2000);
  return { width, height: Math.max(1, Math.round(width / ratio)) };
}

function clamp01(value: number): number {
  return value < 0 ? 0 : value > 1 ? 1 : value;
}

function hslToRgb(h: number, s: number, l: number): { r: number; g: number; b: number } {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = (((h % 360) + 360) % 360) / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  const m = l - c / 2;
  let rgb: [number, number, number];
  if (hp < 1) rgb = [c, x, 0];
  else if (hp < 2) rgb = [x, c, 0];
  else if (hp < 3) rgb = [0, c, x];
  else if (hp < 4) rgb = [0, x, c];
  else if (hp < 5) rgb = [x, 0, c];
  else rgb = [c, 0, x];
  return { r: (rgb[0] + m) * 255, g: (rgb[1] + m) * 255, b: (rgb[2] + m) * 255 };
}
