import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import {
  AiImageSource,
  falImageSize,
  nearestAspectLabel,
  selectAiAdapter,
} from '../../src/images/ai-source.js';
import type { AiAdapterName } from '../../src/images/ai-source.js';
import { probeImage } from '../../src/images/inspect.js';

const AI_KEYS = [
  'OPENAI_API_KEY',
  'XAI_API_KEY',
  'GOOGLE_API_KEY',
  'FAL_KEY',
  'THEMESEED_AI_IMAGE_ADAPTER',
];
const saved: Record<string, string | undefined> = {};

// These tests assert on selection logic, so a developer's real keys in .env
// must not leak in and change which adapter gets chosen.
beforeEach(() => {
  for (const key of AI_KEYS) {
    saved[key] = process.env[key];
    delete process.env[key];
  }
});

afterEach(() => {
  for (const key of AI_KEYS) {
    if (saved[key] === undefined) delete process.env[key];
    else process.env[key] = saved[key];
  }
});

describe('selectAiAdapter', () => {
  it('falls back to procedural when nothing is configured', () => {
    expect(selectAiAdapter({}).name).toBe('procedural');
  });

  it.each([
    ['openaiApiKey', 'openai'],
    ['xaiApiKey', 'grok'],
    ['googleApiKey', 'gemini'],
    ['falKey', 'fal'],
  ] as const)('selects %s -> %s when only that key is present', (option, expected) => {
    expect(selectAiAdapter({ [option]: 'k' }).name).toBe(expected);
  });

  it('honours an explicit choice even when its key is missing', () => {
    // Silently running on a different provider than the one requested would
    // make a misconfiguration invisible.
    const adapter = selectAiAdapter({ adapter: 'gemini' });
    expect(adapter.name).toBe('gemini');
    expect(adapter.isConfigured()).toBe(false);
  });

  it('prefers an explicit choice over an available different key', () => {
    expect(selectAiAdapter({ adapter: 'grok', openaiApiKey: 'k' }).name).toBe('grok');
  });

  it('reads the adapter choice from the environment', () => {
    process.env['THEMESEED_AI_IMAGE_ADAPTER'] = 'fal';
    expect(selectAiAdapter({}).name).toBe('fal');
  });

  it('gives every unconfigured adapter an actionable hint naming its key', () => {
    const expectations: Array<[AiAdapterName, RegExp]> = [
      ['openai', /OPENAI_API_KEY/],
      ['grok', /XAI_API_KEY/],
      ['gemini', /GOOGLE_API_KEY/],
      ['fal', /FAL_KEY/],
    ];
    for (const [name, pattern] of expectations) {
      expect(selectAiAdapter({ adapter: name }).configurationHint()).toMatch(pattern);
    }
  });

  it('warns that Gemini needs billing, since the failure is otherwise cryptic', () => {
    // A key without billing returns 429 instantly, which reads like a rate
    // limit that will clear on its own. It will not.
    expect(selectAiAdapter({ adapter: 'gemini' }).configurationHint()).toMatch(
      /billing/i
    );
  });
});

describe('nearestAspectLabel', () => {
  const supported = ['1:1', '4:3', '3:2', '16:9', '21:9', '3:4', '2:3', '9:16'] as const;

  it.each([
    [1.33, '4:3'],
    [1.5, '3:2'],
    [1.78, '16:9'],
    [2.33, '21:9'],
    [1.0, '1:1'],
    [0.75, '3:4'],
    [0.66, '2:3'],
  ])('snaps ratio %s to %s', (aspectRatio, expected) => {
    expect(nearestAspectLabel({ query: 'x', aspectRatio }, supported)).toBe(expected);
  });

  it('snaps an unsupported ratio to the closest available one', () => {
    // Providers reject arbitrary ratios, so an odd request must still resolve.
    expect(nearestAspectLabel({ query: 'x', aspectRatio: 1.42 }, supported)).toBe('3:2');
  });

  it('defaults to landscape when no ratio is given', () => {
    expect(nearestAspectLabel({ query: 'x' }, supported)).toBe('3:2');
  });

  it('respects an explicit orientation', () => {
    expect(nearestAspectLabel({ query: 'x', orientation: 'portrait' }, supported)).toBe(
      '3:4'
    );
    expect(nearestAspectLabel({ query: 'x', orientation: 'square' }, supported)).toBe(
      '1:1'
    );
  });
});

describe('falImageSize', () => {
  it.each([
    [{ query: 'x', aspectRatio: 1.78 }, 'landscape_16_9'],
    [{ query: 'x', aspectRatio: 1.33 }, 'landscape_4_3'],
    [{ query: 'x', aspectRatio: 1 }, 'square_hd'],
    [{ query: 'x', aspectRatio: 0.75 }, 'portrait_4_3'],
    [{ query: 'x', aspectRatio: 0.56 }, 'portrait_16_9'],
  ])('maps %o to %s', (request, expected) => {
    expect(falImageSize(request)).toBe(expected);
  });
});

describe('AiImageSource with a stub adapter', () => {
  it('rejects generated bytes that are not a decodable image', async () => {
    // A provider returning a JSON error body must not reach the CMS.
    const source = new AiImageSource({
      adapter: {
        name: 'openai',
        isConfigured: () => true,
        configurationHint: () => '',
        generate: async () => [
          {
            bytes: new TextEncoder().encode('{"error":"content policy"}'),
            extension: 'png',
            credit: 'stub',
          },
        ],
      },
    });

    expect(await source.fetch({ query: 'x' }, 1)).toHaveLength(0);
  });

  it('reports the adapter it resolved to', () => {
    expect(new AiImageSource({ adapter: 'grok' }).adapterName).toBe('grok');
  });

  it('throws with the adapter hint when the adapter is unconfigured', async () => {
    const source = new AiImageSource({ adapter: 'fal' });
    await expect(source.fetch({ query: 'x' }, 1)).rejects.toThrow(/not configured/);
  });

  it('writes verified images to disk and reports real dimensions', async () => {
    const { encodePng } = await import('../../src/images/png.js');
    const png = encodePng(64, 48, () => ({ r: 10, g: 20, b: 30 }));

    const source = new AiImageSource({
      adapter: {
        name: 'grok',
        isConfigured: () => true,
        configurationHint: () => '',
        generate: async () => [{ bytes: png, extension: 'png', credit: 'stub credit' }],
      },
    });

    const refs = await source.fetch({ query: 'a building' }, 1);
    expect(refs).toHaveLength(1);
    expect(refs[0]).toMatchObject({ kind: 'file', width: 64, height: 48, source: 'ai' });
    expect(refs[0]?.credit).toBe('stub credit');

    const { promises: fs } = await import('node:fs');
    const written = new Uint8Array(await fs.readFile(refs[0]!.location));
    expect(probeImage(written)).toMatchObject({ width: 64, height: 48 });
  });
});
